singleQuote: true # false 不使用单引号
semi: false # false 不使用分号
trailingComma: 'none' # 在多行数组、对象的最后一项添加逗号，单行数组不会添加。
arrowParens: 'avoid' # 箭头函数只有一个参数时省略括号
endOfLine: 'auto' # 结尾自动换行
singleAttributePerLine: true # true 标签属性使用单行
printWidth: 200 # 单行长度
tabWidth: 2 # 缩进距离
bracketSameLine: true # >符号在末尾，而非另起一行

